### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by ndw** [cmarchand/saxon-support_6578#1]
Hi Christophe,

Could you add a README or something to explain what you are trying to do and what you think doesn't work? I'm having trouble connecting the dots between your original message to the support list and the example code in this repository. Maybe it's just a Monday morning thing, but ...

**Comment by cmarchand** [comment]
Ok, it wasn't clear enough.

Done in #ca74382.

Added real xerces impl to replace buggy jdk xml parsers in #c8032c0

**Comment by cmarchand** [comment]
Close as Readme allowed you to find a solution.

Thanks a lot, @ndw

**Comment by ndw** [comment]
Thanks for the comprehensive test repo. That makes debugging *so* much easier.

**Comment by cmarchand** [comment]
Moving to xspec 3.1.3 which includes your patch solves the problem.

Thanks a lot @ndw !
